version: '3.8'

services:
  jenkins:
    build:
      context: .
    user: root
    container_name: jenkins
    
    ports:
      - "8080:8080"   # Веб-интерфейс Jenkins
      - "50000:50000" # Для подключения агентов (не обязательно для локального использования)
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Для запуска Docker из Jenkins
    environment:
      - JAVA_OPTS=-Duser.timezone=Europe/Moscow
    restart: unless-stopped
    networks:
      - app-network

volumes:
  jenkins_home:

networks:
  app-network:
    driver: bridge